celest-dev/celest

README.md

Update readme to show getting started steps

chore(readme): Update readme to show getting started steps

---

examples/openai/celest/project.dart
examples/openai/lib/main.dart

Update mobile and smaller screen layout.

chore(example): Update example app to have layout work on mobile.

---

packages/celest/CHANGELOG.md
packages/celest/lib/src/runtime/serve.dart
packages/celest/pubspec.yaml

Fixes the route path captured by the heartbeat monitor.

fix(runtime): Route path

---

.github/dependabot.yaml

Adds new packages and fixes syntax

ci: Update dependabot configuration

---

packages/celest_core/lib/src/http/celest_http_client.dart
packages/celest_core/lib/src/http/http_client.vm.dart
packages/celest_core/lib/src/http/http_client.web.dart

This is needed to use cookies.

chore(core): Allow credentials in browser environments

---

.github/workflows/cedar_ffi.yaml
.github/workflows/corks_cedar.yaml
packages/cedar/CHANGELOG.md
packages/cedar/lib/src/policy/cedar_policy.dart
packages/cedar/lib/src/policy/cedar_policy.g.dart
packages/cedar/lib/src/policy/cedar_policy_set.dart
packages/cedar/lib/src/policy/cedar_policy_set.g.dart
packages/cedar/lib/src/policy/json_expr.dart
packages/cedar/lib/src/serializers.dart
packages/cedar/lib/src/serializers.g.dart
packages/cedar/pubspec.yaml
packages/cedar_ffi/.pubignore
packages/cedar_ffi/CHANGELOG.md
packages/cedar_ffi/lib/src/cedar_policy_set_ffi.dart
packages/cedar_ffi/lib/src/ffi/cedar_bindings.g.dart
packages/cedar_ffi/pubspec.yaml
packages/cedar_ffi/src/include/bindings.h
packages/cedar_ffi/src/src/c_api/global.rs
packages/cedar_ffi/test/template_test.dart
packages/corks_cedar/CHANGELOG.md
packages/corks_cedar/lib/src/interop/proto_interop.dart
packages/corks_cedar/pubspec.yaml

Adds support for templates and template-linked policies.

feat(cedar): Template-linked policies

---

packages/celest/CHANGELOG.md
packages/celest/pubspec.yaml
packages/celest_auth/CHANGELOG.md
packages/celest_auth/pubspec.yaml
packages/celest_core/CHANGELOG.md
packages/celest_core/pubspec.yaml

Bump package versions to 0.4.0

chore(version): 0.4.0-dev.1

---

packages/native/storage/CHANGELOG.md
packages/native/storage/pubspec.yaml

- Explicitly adds `platforms` key
- Updates pubspec URL
- Removes unused dependency

chore(native_storage): Clean up pub listing

---

packages/native/storage/CHANGELOG.md
packages/native/storage/lib/src/local/local_storage.android.dart
packages/native/storage/lib/src/native/android/android.dart
packages/native/storage/lib/src/native/android/jni_bindings.ffi.dart
packages/native/storage/lib/src/secure/secure_storage.android.dart
packages/native/storage/pubspec.yaml

Enables isolated Android storage as JNI objects can now be shared via isolates.

chore(native_storage): Migrate to jni 0.8

---

README.md

And add note about repo's license.

chore(repo): Add packages listing to `README`

---

CONTRIBUTING.md

Adds initial contribution guidelines for the repo.

chore(repo): Add `CONTRIBUTORS.md`

---

packages/celest/CHANGELOG.md
packages/celest/pubspec.yaml
packages/celest_auth/CHANGELOG.md
packages/celest_auth/pubspec.yaml
packages/celest_core/pubspec.yaml

- Migrates Celest packages to `package:native_storage`

chore(version): 0.4.0-dev.2

---

.github/workflows/coder.yaml
packages/coder/.gitignore
packages/coder/CHANGELOG.md
packages/coder/LICENSE
packages/coder/README.md
packages/coder/analysis_options.yaml
packages/coder/example/example.dart
packages/coder/lib/coder.dart
packages/coder/lib/src/coder.dart
packages/coder/lib/src/decoder.dart
packages/coder/lib/src/encoder.dart
packages/coder/lib/src/form_data/form_data_coder.dart
packages/coder/lib/src/form_data/form_data_encoder.dart
packages/coder/lib/src/form_fields/form_fields_coder.dart
packages/coder/lib/src/form_fields/form_fields_encoder.dart
packages/coder/lib/src/json/json_coder.dart
packages/coder/lib/src/json/json_decoder.dart
packages/coder/lib/src/json/json_encoder.dart
packages/coder/lib/src/typeref.dart
packages/coder/pubspec.yaml
packages/coder/test/coder_test.dart

Adds `package:coder`, a general-purpose serialization framework based on Swift Codable.

feat: `package:coder`

---

packages/celest/CHANGELOG.md
packages/celest/pubspec.yaml
packages/celest_auth/CHANGELOG.md
packages/celest_auth/pubspec.yaml

Fixes: https://github.com/dart-lang/pana/issues/1351

fix: Pana issues

---

packages/celest/CHANGELOG.md
packages/celest/pubspec.yaml
packages/celest_core/CHANGELOG.md
packages/celest_core/pubspec.yaml

Adds support for event streaming via SSE/WebSockets

chore(version): 0.4.2

---

.github/workflows/celest_cloud.yaml
packages/celest_auth/example/lib/main.dart
packages/celest_auth/lib/src/auth_impl.dart
packages/celest_auth/lib/src/flows/email_flow.dart
packages/celest_auth/lib/src/flows/idp_flow.dart
packages/celest_auth/lib/src/model/cloud_interop.dart
packages/celest_auth/lib/src/model/initial_uri.dart
packages/celest_auth/lib/src/model/initial_uri.flutter.dart
packages/celest_auth/lib/src/model/initial_uri.stub.dart
packages/celest_auth/lib/src/model/initial_uri.web.dart
packages/celest_auth/lib/src/state/auth_state.dart
packages/celest_auth/lib/src/version.dart
packages/celest_auth/pubspec.yaml
packages/celest_cloud/lib/celest_cloud.dart
packages/celest_cloud/lib/src/cloud/base/base_service.dart
packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/organizations.pbjson.dart
packages/celest_cloud/lib/src/proto/operations.dart
packages/celest_core/lib/src/exception/cloud_exception.dart

- Updates celest_auth to use Celest Cloud API
- Adds IDP authentication support

feat(celest_auth): Update with IDP + Celest Cloud integration

---

packages/celest/lib/http.dart
packages/celest_cloud/lib/src/cloud/authentication/authentication_protocol.http.dart
packages/celest_cloud/lib/src/cloud/base/base_protocol.dart
packages/celest_cloud/lib/src/cloud/base/base_service.dart
packages/celest_cloud/lib/src/cloud/operations/operations_protocol.http.dart
packages/celest_cloud/lib/src/cloud/organizations/organizations_protocol.http.dart
packages/celest_cloud/lib/src/cloud/users/users_protocol.http.dart
packages/celest_core/analysis_options.yaml
packages/celest_core/lib/_internal.dart
packages/celest_core/lib/src/base/base_protocol.dart
packages/celest_core/lib/src/exception/cloud_exception.dart
packages/celest_core/lib/src/exception/serialization_exception.dart
packages/celest_core/lib/src/http/http_error.dart

Makes them integrate better with auto-serialization.

chore: Clean up exception types

---

packages/celest/lib/src/auth/auth_provider.dart
packages/celest/lib/src/config/env.dart
packages/celest/lib/src/core/context.dart
packages/celest/pubspec.yaml

- Adds support for remaining auth providers
- Adds support for secrets

feat: Add remaining auth providers and secrets

---

packages/celest_ast/CHANGELOG.md
packages/celest_ast/lib/src/resolved_ast.dart
packages/celest_ast/pubspec.yaml
packages/celest_ast/test/celest_ast_test.dart

Adds a missing switch case in the proto interop code.

fix(ast): Add missing switch case

---

packages/celest/lib/src/data/database.dart
packages/celest/pubspec.yaml
packages/celest_ast/CHANGELOG.md
packages/celest_ast/lib/src/ast.dart
packages/celest_ast/lib/src/ast.g.dart
packages/celest_ast/lib/src/proto/celest/ast/v1/resolved_ast.pb.dart
packages/celest_ast/lib/src/proto/celest/ast/v1/resolved_ast.pbenum.dart
packages/celest_ast/lib/src/proto/celest/ast/v1/resolved_ast.pbjson.dart
packages/celest_ast/lib/src/resolved_ast.dart
packages/celest_ast/lib/src/resolved_ast.g.dart
packages/celest_ast/lib/src/serializers.dart
packages/celest_ast/lib/src/serializers.g.dart
packages/celest_ast/lib/src/visitor.dart
packages/celest_ast/proto/celest/ast/v1/resolved_ast.proto
packages/celest_ast/pubspec.yaml
packages/celest_ast/test/celest_ast_test.dart

- Adds `Database` and `Schema` types for configuring data providers
- Adds corresponding AST models for resolution

feat(data): Celest Data types

---

examples/tasks/celest/lib/src/database/task_database.g.dart
examples/tasks/celest/pubspec.yaml
packages/celest/pubspec.yaml
services/celest_cloud_auth/lib/src/database/schema/auth.drift.dart
services/celest_cloud_auth/lib/src/database/schema/cedar.drift.dart
services/celest_cloud_auth/lib/src/database/schema/invocations.drift.dart
services/celest_cloud_auth/lib/src/database/schema/projects.drift.dart
services/celest_cloud_auth/lib/src/database/schema/users.drift.dart
services/celest_cloud_auth/pubspec.yaml

Minor version bumps seem to cause breaking changes generated code.

chore: Pin `drift` to minor version

---

README.md
services/celest_cloud_auth/CHANGELOG.md
services/celest_cloud_auth/lib/src/database/auth_database.dart
services/celest_cloud_auth/lib/src/model/route_map.dart
services/celest_cloud_auth/pubspec.yaml

chore(cloud_auth): Remove some leftover print statements

---

.github/workflows/celest.yaml
.github/workflows/celest_ast.yaml
.github/workflows/celest_auth.yaml
.github/workflows/celest_cli.yaml
.github/workflows/celest_cloud.yaml
.github/workflows/celest_cloud_auth.yaml
.github/workflows/celest_core.yaml
.github/workflows/examples.yaml
CONTRIBUTING.md
apps/cli/pubspec.yaml
apps/cli/test/pub/pub_action_test.dart
packages/celest/lib/celest.dart
packages/celest/lib/http.dart
packages/celest/pubspec.yaml
packages/celest_ast/analysis_options.yaml
packages/celest_ast/pubspec.yaml
packages/celest_auth/pubspec.yaml
packages/celest_cloud/pubspec.yaml
packages/celest_core/pubspec.yaml
packages/celest_lints/pubspec.yaml
pubspec.yaml
services/celest_cloud_auth/pubspec.yaml

Should fix remaining CI errors with melos

chore: Migrate to pub workspace

---

.github/workflows/celest.yaml
packages/celest/example/.gitignore
packages/celest/example/android/.gitignore
packages/celest/example/android/build.gradle
packages/celest/example/android/gradle/wrapper/gradle-wrapper.properties
packages/celest/example/android/settings.gradle
packages/celest/example/celest/client/lib/example_client.dart
packages/celest/example/celest/client/pubspec.yaml
packages/celest/example/celest/pubspec.yaml
packages/celest/example/integration_test/integration_test.dart
packages/celest/example/ios/Podfile
packages/celest/example/ios/Podfile.lock
packages/celest/example/ios/Runner.xcodeproj/project.pbxproj
packages/celest/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/celest/example/ios/Runner/AppDelegate.swift
packages/celest/example/macos/Podfile
packages/celest/example/macos/Podfile.lock
packages/celest/example/macos/Runner.xcodeproj/project.pbxproj
packages/celest/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/celest/example/macos/Runner/AppDelegate.swift
packages/celest/example/pubspec.yaml
packages/celest/example/test_driver/integration_test.dart
packages/celest/example/web/index.html
packages/celest_core/lib/src/util/globals.dart
packages/celest_core/test/util/globals_test.dart

- Updates example app with latest Flutter changes
- Adds an integration test to test platform-specific behavior

chore(celest): Update example

---

apps/cli/fixtures/fixtures_test.dart
apps/cli/lib/src/codegen/client/client_generator.dart
apps/cli/lib/src/frontend/celest_frontend.dart
apps/cli/lib/src/project/project_linker.dart
apps/cli/pubspec.yaml

- Ensure we call `_auth.init` only after initialization
- Ensure auth APIs are linked in the resolved AST

fix(cli): Auth issues

---

packages/celest/CHANGELOG.md
packages/celest/pubspec.yaml
packages/celest_ast/CHANGELOG.md
packages/celest_ast/pubspec.yaml
packages/celest_auth/CHANGELOG.md
packages/celest_auth/pubspec.yaml
packages/celest_core/CHANGELOG.md
packages/celest_core/pubspec.yaml
services/celest_cloud_auth/CHANGELOG.md
services/celest_cloud_auth/pubspec.yaml

Updates CHANGELOGs and pubspec.yaml files throughout for first open-source launch.

chore: Prepare for publishing

---

apps/cli/fixtures/standalone/auth/client/lib/src/functions.dart
apps/cli/fixtures/standalone/streaming/client/lib/src/functions.dart
apps/cli/lib/src/codegen/client/categories/client_functions_generator.dart

Errors are returned in the `@status` field not the `@error` field.

fix(cli): Websocket error condition

---

apps/cli/bin/celest.dart

Need to re-implement to work with `pub` installation.

chore(cli): Remove `upgrade` command for now

---

services/celest_cloud_auth/CHANGELOG.md
services/celest_cloud_auth/lib/src/authorization/authorizer.dart
services/celest_cloud_auth/pubspec.yaml

So that it can be implemented for fakes.

chore(cloud_auth): Make `Authorizer` a class

---

.github/workflows/celest_cli.yaml
.github/workflows/celest_cloud_hub.yaml
pubspec.yaml
services/celest_cloud_hub/.dockerignore
services/celest_cloud_hub/.gitignore
services/celest_cloud_hub/CHANGELOG.md
services/celest_cloud_hub/Dockerfile
services/celest_cloud_hub/README.md
services/celest_cloud_hub/analysis_options.yaml
services/celest_cloud_hub/bin/cloud_hub.dart
services/celest_cloud_hub/build.yaml
services/celest_cloud_hub/lib/celest_cloud_hub.dart
services/celest_cloud_hub/lib/src/auth/auth_interceptor.dart
services/celest_cloud_hub/lib/src/database/cloud_hub_database.dart
services/celest_cloud_hub/lib/src/database/cloud_hub_database.g.dart
services/celest_cloud_hub/lib/src/database/db_functions.dart
services/celest_cloud_hub/lib/src/database/schema/operations.drift
services/celest_cloud_hub/lib/src/database/schema/project_environments.drift
services/celest_cloud_hub/lib/src/gateway/gateway.dart
services/celest_cloud_hub/lib/src/gateway/gateway_handler.dart
services/celest_cloud_hub/lib/src/model/lifecycle_state.dart
services/celest_cloud_hub/lib/src/model/operation.dart
services/celest_cloud_hub/lib/src/model/protobuf.dart
services/celest_cloud_hub/lib/src/model/type_registry.dart
services/celest_cloud_hub/lib/src/project.dart
services/celest_cloud_hub/lib/src/services/operations_service.dart
services/celest_cloud_hub/lib/src/services/project_environments_service.dart
services/celest_cloud_hub/pubspec.yaml
services/celest_cloud_hub/test/services/operations_service_test.dart

Adds the initial scaffolding of a slim Cloud Hub which manages the provisioning and deployment of Celest projects.

feat(cloud_hub): Add initial Hub package

---

services/celest_cloud_hub/.dockerignore
services/celest_cloud_hub/Dockerfile
services/celest_cloud_hub/analysis_options.yaml
services/celest_cloud_hub/bin/cloud_hub.dart
services/celest_cloud_hub/build.sh
services/celest_cloud_hub/deploy.sh
services/celest_cloud_hub/fly.yaml
services/celest_cloud_hub/lib/src/gateway/gateway.dart
services/celest_cloud_hub/lib/src/project.dart
services/celest_cloud_hub/lib/src/proto/health/v1/health.pb.dart
services/celest_cloud_hub/lib/src/proto/health/v1/health.pbenum.dart
services/celest_cloud_hub/lib/src/proto/health/v1/health.pbgrpc.dart
services/celest_cloud_hub/lib/src/proto/health/v1/health.pbjson.dart
services/celest_cloud_hub/lib/src/services/health_service.dart
tool/fix_pub_cache.dart

Adds configuration for building a Docker container of the Cloud Hub and deploying to Fly.io

feat(cloud_hub): Add fly deployment config

---

apps/cli/fixtures/standalone/auth/goldens/ast.resolved.json
apps/cli/fixtures/standalone/auth/goldens/celest.json
apps/cli/fixtures/standalone/data/goldens/ast.resolved.json
apps/cli/fixtures/standalone/data/goldens/celest.json
packages/celest_cloud/lib/src/cloud/base/base_protocol.dart
services/celest_cloud_auth/CHANGELOG.md
services/celest_cloud_auth/lib/src/authorization/cedar/policies.cedar
services/celest_cloud_auth/lib/src/authorization/policy_set.g.dart
services/celest_cloud_auth/lib/src/context.dart
services/celest_cloud_auth/lib/src/users/users_service.dart
services/celest_cloud_auth/test/users/users_service_test.dart

Fix routing of `users/me` endpoint to correctly alias to invoking principal.

fix(cloud_auth): Correctly route `users/me`

---

apps/cli/lib/src/context.dart
apps/cli/lib/src/frontend/celest_frontend.dart
examples/tasks/celest/client/lib/tasks_client.dart
packages/celest/lib/src/runtime/http/cloud_middleware.dart
packages/celest_cloud/lib/src/cloud/cloud.dart
services/celest_cloud_auth/lib/src/authorization/authorization_middleware.dart
services/celest_cloud_hub/Dockerfile
services/celest_cloud_hub/bin/cloud_hub.dart
services/celest_cloud_hub/build.sh
services/celest_cloud_hub/deploy.sh
services/celest_cloud_hub/fly.yaml
services/celest_cloud_hub/lib/src/database/cloud_hub_database.dart
services/celest_cloud_hub/lib/src/gateway/gateway.dart
services/celest_cloud_hub/lib/src/services/project_environments_service.dart
services/celest_cloud_hub/pubspec.yaml

- Update fly config to use DB volume for database
- Add Sentry configuration
- Fix integration with CLI

chore(cloud_hub): Prep for production

---

apps/distroless/bin/list_sdks.dart
apps/distroless/dart/build/Dockerfile
apps/distroless/flutter/build/Dockerfile
services/celest_cloud_hub/Dockerfile
services/celest_cloud_hub/bin/cloud_hub.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_deployment_engine.dart

- Updates cloud_hub to use distroless base images
- Updates distroless Dart to use the `base` variant which includes ca-certs

chore(cloud_hub): Updates to use distroless base images

---

apps/cli/CHANGELOG.md
apps/cli/lib/src/frontend/celest_frontend.dart
apps/cli/lib/src/logging/cli_logger.dart
apps/cli/lib/src/repositories/organization_repository.dart
apps/cli/lib/src/repositories/project_environment_repository.dart
apps/cli/lib/src/repositories/project_repository.dart

- Fix control character handling on secret input
- Make repos into extension types
- Ensure cloud commands are try/catch'd

chore(cli): Minor fixes

---

apps/cli/CHANGELOG.md
apps/cli/fixtures/standalone/api/goldens/ast.json
apps/cli/fixtures/standalone/api/goldens/ast.resolved.json
apps/cli/fixtures/standalone/api/goldens/celest.json
apps/cli/fixtures/standalone/auth/goldens/ast.json
apps/cli/fixtures/standalone/auth/goldens/ast.resolved.json
apps/cli/fixtures/standalone/auth/goldens/celest.json
apps/cli/fixtures/standalone/data/goldens/ast.json
apps/cli/fixtures/standalone/data/goldens/ast.resolved.json
apps/cli/fixtures/standalone/data/goldens/celest.json
apps/cli/fixtures/standalone/env_vars/goldens/ast.json
apps/cli/fixtures/standalone/env_vars/goldens/ast.resolved.json
apps/cli/fixtures/standalone/env_vars/goldens/celest.json
apps/cli/fixtures/standalone/exceptions/goldens/ast.json
apps/cli/fixtures/standalone/exceptions/goldens/ast.resolved.json
apps/cli/fixtures/standalone/exceptions/goldens/celest.json
apps/cli/fixtures/standalone/flutter/goldens/ast.json
apps/cli/fixtures/standalone/flutter/goldens/ast.resolved.json
apps/cli/fixtures/standalone/flutter/goldens/celest.json
apps/cli/fixtures/standalone/http/goldens/ast.json
apps/cli/fixtures/standalone/http/goldens/ast.resolved.json
apps/cli/fixtures/standalone/http/goldens/celest.json
apps/cli/fixtures/standalone/marcelo/goldens/ast.json
apps/cli/fixtures/standalone/marcelo/goldens/ast.resolved.json
apps/cli/fixtures/standalone/marcelo/goldens/celest.json
apps/cli/fixtures/standalone/streaming/goldens/ast.json
apps/cli/fixtures/standalone/streaming/goldens/ast.resolved.json
apps/cli/fixtures/standalone/streaming/goldens/celest.json
apps/cli/lib/src/version.dart
apps/cli/pubspec.yaml

- fix: Handle control characters when prompting for secrets

release(cli): v1.0.10+1

---

apps/cli/CHANGELOG.md
apps/cli/lib/src/cli/cli.dart
apps/cli/lib/src/context.dart
apps/cli/lib/src/performance/local_perf.dart
apps/cli/lib/src/performance/sentry_perf.dart

Ensure Sentry integration handles all errors raised and respects NO_ANALYTICS setting.

fix(cli): Sentry integration

---

apps/cli/CHANGELOG.md
apps/cli/lib/src/commands/auth/logout_command.dart
apps/cli/lib/src/config/celest_config.dart
apps/cli/lib/src/init/project_init.dart
apps/cli/lib/src/project/celest_project.dart
apps/cli/lib/src/pub/pub_cache.dart
apps/cli/test/commands/uninstall_test.dart
apps/cli/test/config/celest_config_test.dart
apps/cli/test/pub/pub_cache_test.dart

Perform pub cache fixes during initialization if needed to ensure projects do not default to using Flutter SDK.

fix(cli): Ensure pub cache is fixed during startup

---

packages/celest_cloud/CHANGELOG.md
packages/celest_cloud/pubspec.yaml

- feat: Add `ProjectAsset.FLUTTER_ASSETS`

release(celest_cloud): v0.1.7

---

apps/cli/CHANGELOG.md
apps/cli/fixtures/standalone/api/goldens/ast.json
apps/cli/fixtures/standalone/api/goldens/ast.resolved.json
apps/cli/fixtures/standalone/api/goldens/celest.json
apps/cli/fixtures/standalone/auth/goldens/ast.json
apps/cli/fixtures/standalone/auth/goldens/ast.resolved.json
apps/cli/fixtures/standalone/auth/goldens/celest.json
apps/cli/fixtures/standalone/data/goldens/ast.json
apps/cli/fixtures/standalone/data/goldens/ast.resolved.json
apps/cli/fixtures/standalone/data/goldens/celest.json
apps/cli/fixtures/standalone/env_vars/goldens/ast.json
apps/cli/fixtures/standalone/env_vars/goldens/ast.resolved.json
apps/cli/fixtures/standalone/env_vars/goldens/celest.json
apps/cli/fixtures/standalone/exceptions/goldens/ast.json
apps/cli/fixtures/standalone/exceptions/goldens/ast.resolved.json
apps/cli/fixtures/standalone/exceptions/goldens/celest.json
apps/cli/fixtures/standalone/flutter/goldens/ast.json
apps/cli/fixtures/standalone/flutter/goldens/ast.resolved.json
apps/cli/fixtures/standalone/flutter/goldens/celest.json
apps/cli/fixtures/standalone/http/goldens/ast.json
apps/cli/fixtures/standalone/http/goldens/ast.resolved.json
apps/cli/fixtures/standalone/http/goldens/celest.json
apps/cli/fixtures/standalone/marcelo/goldens/ast.json
apps/cli/fixtures/standalone/marcelo/goldens/ast.resolved.json
apps/cli/fixtures/standalone/marcelo/goldens/celest.json
apps/cli/fixtures/standalone/streaming/goldens/ast.json
apps/cli/fixtures/standalone/streaming/goldens/ast.resolved.json
apps/cli/fixtures/standalone/streaming/goldens/celest.json
apps/cli/lib/src/version.dart
apps/cli/pubspec.yaml

- feat: Add `celest auth token` command
- feat: Add `celest auth whoami` command
- feat: Add `--token` parameter to `auth login`

release(cli): v1.0.11

---

packages/celest_cloud/CHANGELOG.md
packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/project_environments.pbenum.dart
packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/project_environments.pbjson.dart
packages/celest_cloud/pubspec.yaml
proto/celest/cloud/v1alpha1/project_environments.proto

To support cross-compilation on the frontend, add a new project asset type for sending to the backend.

feat(celest_cloud): Add `ProjectAsset_Type.DART_EXECUTABLE`

---

.github/workflows/distroless_core.yaml
.github/workflows/distroless_dart.yaml
apps/cli/fixtures/fixtures_test.dart
apps/cli/lib/src/codegen/api/dockerfile_generator.dart
apps/cli/lib/src/compiler/api/entrypoint_compiler.dart
apps/cli/lib/src/frontend/celest_frontend.dart
apps/cli/lib/src/sdk/dart_sdk.dart
apps/distroless/core/Dockerfile
services/celest_cloud_hub/bin/deploy_test.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_deployment_engine.dart
services/celest_cloud_hub/lib/src/services/project_environments_service.dart

Dart 3.8 will support cross-compilation via the `dart compile exe` command. When available, use this instead for faster deployments.

feat(cli): Support cross-compilation

---

.github/workflows/distroless_dart.yaml
.github/workflows/distroless_flutter.yaml
apps/cli/fixtures/fixtures_test.dart
apps/distroless/dart/test/test-docker.sh
apps/distroless/flutter/test/test-docker.sh

Fix tests for distroless containers which were always testing the same dart/flutter version.

ci(distroless): Fix tests

---

apps/cli/tool/linux/deb/DEBIAN/postinst
apps/cli/tool/linux/deb/DEBIAN/postrm
apps/cli/tool/release.dart

- Ensure `celest` is installed to PATH
- Ensure .deb is generated with correct architecture

ci: Fix Debian installer

---

apps/cli/CHANGELOG.md
apps/cli/fixtures/standalone/api/goldens/ast.json
apps/cli/fixtures/standalone/api/goldens/ast.resolved.json
apps/cli/fixtures/standalone/api/goldens/celest.json
apps/cli/fixtures/standalone/auth/goldens/ast.json
apps/cli/fixtures/standalone/auth/goldens/ast.resolved.json
apps/cli/fixtures/standalone/auth/goldens/celest.json
apps/cli/fixtures/standalone/data/goldens/ast.json
apps/cli/fixtures/standalone/data/goldens/ast.resolved.json
apps/cli/fixtures/standalone/data/goldens/celest.json
apps/cli/fixtures/standalone/env_vars/goldens/ast.json
apps/cli/fixtures/standalone/env_vars/goldens/ast.resolved.json
apps/cli/fixtures/standalone/env_vars/goldens/celest.json
apps/cli/fixtures/standalone/exceptions/goldens/ast.json
apps/cli/fixtures/standalone/exceptions/goldens/ast.resolved.json
apps/cli/fixtures/standalone/exceptions/goldens/celest.json
apps/cli/fixtures/standalone/flutter/goldens/ast.json
apps/cli/fixtures/standalone/flutter/goldens/ast.resolved.json
apps/cli/fixtures/standalone/flutter/goldens/celest.json
apps/cli/fixtures/standalone/http/goldens/ast.json
apps/cli/fixtures/standalone/http/goldens/ast.resolved.json
apps/cli/fixtures/standalone/http/goldens/celest.json
apps/cli/fixtures/standalone/marcelo/goldens/ast.json
apps/cli/fixtures/standalone/marcelo/goldens/ast.resolved.json
apps/cli/fixtures/standalone/marcelo/goldens/celest.json
apps/cli/fixtures/standalone/streaming/goldens/ast.json
apps/cli/fixtures/standalone/streaming/goldens/ast.resolved.json
apps/cli/fixtures/standalone/streaming/goldens/celest.json
apps/cli/lib/src/version.dart
apps/cli/pubspec.yaml

- feat: Support cross-compilation with Dart 3.8
- feat: Ensure primary org creation on login
- feat: Add Linux installer

release(cli): v1.0.12

---

apps/cli/lib/src/commands/celest_command.dart

This was getting printed for every command registered.

chore(cli): Fix log statement

---

apps/cli/lib/src/commands/auth/authenticate.dart
apps/cli/lib/src/commands/auth/login_command.dart
apps/cli/lib/src/exceptions.dart
apps/cli/lib/src/logging/cli_logger.dart
apps/cli/lib/src/repositories/cloud_repository.dart
apps/cli/pubspec.yaml
apps/cli/test/e2e/common/common.dart
apps/cli/test/e2e/common/test_cloud.dart
apps/cli/test/e2e/e2e_test.dart
apps/cli/test/e2e/tests/bugs/add_remove_fields.dart
apps/cli/test/e2e/tests/commands/auth/login_command.dart
apps/cli/test/e2e/tests/commands/start/start_child_process.dart

Adds an E2E test w/ Cloud Hub for `celest auth login`.

test(cli): Add E2E test for login

---

.github/workflows/celest_cli.e2e.yaml
apps/cli/lib/src/context.dart
apps/cli/lib/src/frontend/child_process.dart
apps/cli/lib/src/logging/cli_json_logger.dart
apps/cli/lib/src/logging/cli_logger.dart
apps/cli/test/e2e/common/common.dart
apps/cli/test/e2e/common/test_cloud.dart
apps/cli/test/e2e/common/test_projects.dart
apps/cli/test/e2e/e2e_test.dart
apps/cli/test/e2e/tests/commands/start/hot_reload/hot_reload_add_auth.dart
apps/cli/test/e2e/tests/commands/start/hot_reload/hot_reload_add_model_after_error.dart
apps/cli/test/e2e/tests/commands/start/start_flutter_child_process.dart

- Adds a test for `package:celest_test`
- Updates skips for some E2E tests

test(cli): Add E2E test for `package:celest_test`

---

.github/workflows/celest_cloud_hub.yaml
services/celest_cloud_hub/bin/_delete_test_apps.dart
services/celest_cloud_hub/fly.yaml
services/celest_cloud_hub/lib/src/context.dart
services/celest_cloud_hub/lib/src/database/cloud_hub_database.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_api.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_api_client.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_caveat.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_ctl.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_deployment_engine.dart
services/celest_cloud_hub/lib/src/services/organizations_service.dart
services/celest_cloud_hub/lib/src/services/project_environments_service.dart
services/celest_cloud_hub/lib/src/services/projects_service.dart
services/celest_cloud_hub/test/common.dart
services/celest_cloud_hub/test/deploy/deploy_test_app.dart
services/celest_cloud_hub/test/deploy/fly_attenuate_test.dart
services/celest_cloud_hub/test/deploy/fly_deployment_engine_test.dart
services/celest_cloud_hub/test/e2e_tester.dart
services/celest_cloud_hub/test/services/operations_service_e2e_test.dart
services/celest_cloud_hub/test/services/operations_service_test.dart
services/celest_cloud_hub/test/services/organizations_service_e2e_test.dart
services/celest_cloud_hub/test/services/organizations_service_test.dart
services/celest_cloud_hub/test/services/project_environments_service_e2e_test.dart
services/celest_cloud_hub/test/services/project_environments_service_test.dart
services/celest_cloud_hub/test/services/projects_service_e2e_test.dart
services/celest_cloud_hub/test/services/projects_service_test.dart

Adds the ability to attenuate tokens for Fly.io.
Includes a lot of refactoring + tests for deploying and attenuating.

feat(cloud_hub): Add fly token attenuation

---

services/celest_cloud_auth/CHANGELOG.md
services/celest_cloud_auth/pubspec.yaml

- fix: Migration of Cloud Auth tables
- perf: Use batches for migrations

release(cloud_auth): v0.3.3

---

examples/gemini/celest/client/lib/gemini_example_client.dart
examples/tasks/celest/.gitignore
examples/tasks/celest/client/lib/src/functions.dart
examples/tasks/celest/client/lib/src/serializers.dart
examples/tasks/celest/client/lib/tasks_client.dart
services/celest_cloud_hub/bin/cloud_hub.dart
services/celest_cloud_hub/lib/src/context.dart
services/celest_cloud_hub/lib/src/deploy/deployment_engine.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_api.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_api_client.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_deployment_engine.dart

Properly detaches volumes from running machines before disposing.

fix(cloud_hub): Migration of volumes to Turso

---

services/celest_cloud_hub/bin/run_migrations.dart
services/celest_cloud_hub/deploy.sh
services/celest_cloud_hub/fly.yaml
services/celest_cloud_hub/lib/src/deploy/fly/fly_api.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_app_config.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_app_config.g.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_ctl.dart
services/celest_cloud_hub/lib/src/deploy/fly/fly_deployment_engine.dart

- Switch primary region to ewr
- Add health checks for hub and deployed apps

chore(cloud_hub): Update deployment config

---

.github/workflows/celest_ast.yaml
packages/celest_ast/CHANGELOG.md
packages/celest_ast/analysis_options.yaml
packages/celest_ast/lib/src/ast.dart
packages/celest_ast/lib/src/ast.g.dart
packages/celest_ast/lib/src/dart_value.dart
packages/celest_ast/lib/src/dart_value.g.dart
packages/celest_ast/lib/src/resolved_ast.dart
packages/celest_ast/lib/src/resolved_ast.g.dart
packages/celest_ast/lib/src/sdk_configuration.dart
packages/celest_ast/lib/src/sdk_configuration.g.dart
packages/celest_ast/lib/src/serializers.dart
packages/celest_ast/lib/src/serializers.g.dart
packages/celest_ast/lib/src/visitor.dart
packages/celest_ast/pubspec.yaml
packages/celest_ast/test/celest_ast_test.dart

chore(ast): Update linter/style preferences

---

.github/workflows/celest_core.yaml
packages/celest_core/CHANGELOG.md
packages/celest_core/analysis_options.yaml
packages/celest_core/lib/src/auth/auth_client.dart
packages/celest_core/lib/src/auth/auth_protocol.dart
packages/celest_core/lib/src/auth/authenticator.dart
packages/celest_core/lib/src/auth/otp/otp_types.dart
packages/celest_core/lib/src/auth/user.dart
packages/celest_core/lib/src/base/base_protocol.dart
packages/celest_core/lib/src/events/event_channel.vm.dart
packages/celest_core/lib/src/events/event_channel.web.dart
packages/celest_core/lib/src/events/event_client.dart
packages/celest_core/lib/src/events/sse/sse_client.web.dart
packages/celest_core/lib/src/exception/cloud_exception.dart
packages/celest_core/lib/src/http/celest_http_client.dart
packages/celest_core/lib/src/http/http_status.dart
packages/celest_core/lib/src/serialization/json_value.dart
packages/celest_core/lib/src/serialization/serializer.dart
packages/celest_core/lib/src/serialization/serializers/cloud_exception_serializer.dart
packages/celest_core/lib/src/serialization/serializers/duration_serializer.dart
packages/celest_core/lib/src/util/base64_raw_url.dart
packages/celest_core/lib/src/util/json.dart
packages/celest_core/lib/src/util/uuid.dart
packages/celest_core/test/serialization/json_value_test.dart

chore(core): Update linter/style preferences

---

.github/workflows/celest_db_studio.yaml
packages/celest_db_studio/CHANGELOG.md
packages/celest_db_studio/analysis_options.yaml
packages/celest_db_studio/bin/server.dart
packages/celest_db_studio/lib/celest_db_studio.dart
packages/celest_db_studio/lib/src/driver.dart
packages/celest_db_studio/test/e2e_test.dart
packages/celest_db_studio/test/server_test.dart
packages/celest_db_studio/test/start_server.dart

chore(db_studio): Update linter/style preferences

---

.github/workflows/celest_test.yaml
packages/celest_test/CHANGELOG.md
packages/celest_test/lib/celest_test.dart
packages/celest_test/lib/src/vm_service_factory.dart

chore(test): Update linter/style preferences

---

.github/workflows/celest_core.yaml
packages/celest_core/CHANGELOG.md
packages/celest_core/pubspec.yaml

- chore: Update dependencies
- chore: Update linter/style preferences
- chore: Bump Dart SDK constraint to `^3.7.0`
- chore: Re-format with Dart 3.7

release(core): v1.0.3

---

.github/workflows/celest_db_studio.yaml
packages/celest_db_studio/LICENSE
packages/celest_db_studio/pubspec.yaml

release(db_studio): v0.1.0

---

README.md

- Remove warning
- Update example's syntax
- Add missing packages to tables

chore(repo): Update README

---

apps/cli/fixtures/standalone/data/pubspec.yaml
apps/cli/lib/src/pub/project_dependency.dart
apps/cli/pubspec.yaml
apps/distroless/dart/test/pubspec.yaml
apps/distroless/flutter/test/pubspec.yaml
examples/tasks/celest/pubspec.yaml
pubspec.yaml

Updates upper bound to allow drift v2.28.x

chore(deps): Allow latest `drift`

---

packages/celest_test/CHANGELOG.md
packages/celest_test/pubspec.yaml

- chore: Update dependencies
- chore: Update linter/style preferences

release(celest_test): v0.1.1

---

packages/celest_cloud/CHANGELOG.md
packages/celest_cloud/pubspec.yaml

- chore: Fix lint errors
- chore: Update protobufs

release(cloud): v0.1.10

---

services/celest_cloud_core/CHANGELOG.md
services/celest_cloud_core/pubspec.yaml

release(cloud_core): v0.1.1

---

services/celest_cloud_auth/CHANGELOG.md
services/celest_cloud_auth/pubspec.yaml

release(cloud_auth): v0.3.5
