- README.md
Apparently the website shows a Page Not Found for less than a millisecond to then show the content, removing the last / from the URL seems to be the "correct" url for that page.
> docs: `about-us` link shows `Page Not Found` for a fraction of a second

- packages/celest/example/celest/lib/client.dart
- packages/celest/example/celest/lib/exceptions.dart
- packages/celest/example/celest/lib/models.dart
- packages/celest/example/celest/pubspec.yaml
- packages/celest/example/lib/main.dart
- packages/celest/example/pubspec.yaml
Renames Celest project package to `celest_backend` by convention.
> chore: Rename Celest project package

- packages/celest_core/CHANGELOG.md
- packages/celest_core/lib/src/serialization/serializer.dart
While this exception can be thrown on the client or server, it is only thrown on the client by fault of the user. And there is only one reason why this would be the case.
> chore(core): Improve SerializationException message

- packages/celest_core/CHANGELOG.md
- packages/celest_core/lib/src/exception/cloud_exception.dart
- packages/celest_core/lib/src/exception/serialization_exception.dart
When thrown on the server, a serialization exception means that the server received bad data from the client.
> chore(core): Make `SerializationException` implement `BadRequestException`

- LICENSE
- packages/celest/LICENSE
- packages/celest_core/LICENSE
This avoids the need to introduce the dual MIT/Apache-2 licensing structure many projects use while providing all the legal affordances.
> chore(repo): Relicense as BSD+Patent

- packages/cedar/.gitignore
- packages/cedar/CHANGELOG.md
- packages/cedar/README.md
- packages/cedar/analysis_options.yaml
- packages/cedar/lib/cedar.dart
- packages/cedar/lib/src/ast/cedar_entity.dart
- packages/cedar/lib/src/ast/cedar_entity.g.dart
- packages/cedar/lib/src/ast/cedar_entity_id.dart
- packages/cedar/lib/src/ast/cedar_entity_id.g.dart
- packages/cedar/lib/src/ast/cedar_schema.dart
- packages/cedar/lib/src/authorization/cedar_authorization_request.dart
- packages/cedar/lib/src/authorization/cedar_authorization_response.dart
- packages/cedar/lib/src/authorization/cedar_authorizer.dart
- packages/cedar/lib/src/policy/cedar_policy.dart
- packages/cedar/lib/src/policy/cedar_policy.g.dart
- packages/cedar/lib/src/policy/cedar_policy_set.dart
- packages/cedar/lib/src/policy/cedar_policy_set.g.dart
- packages/cedar/lib/src/policy/json_expr.dart
- packages/cedar/lib/src/serializers.dart
- packages/cedar/lib/src/serializers.g.dart
- packages/cedar/lib/src/util.dart
- packages/cedar/pubspec.yaml
Adds `package:cedar` which includes Dart representations of the Cedar policy language and shared interfaces which will be implemented in `package:cedar_ffi`.
> feat: Add `package:cedar`

- packages/celest_core/lib/src/storage/secure/secure_storage.darwin.dart
Removes `kSecMatchLimit` from write and delete queries which was accidentally added.
> fix(ios): Secure storage query

- packages/celest/pubspec.yaml
- packages/celest/pubspec_overrides.yaml
- packages/celest_auth/example/celest/pubspec.yaml
- packages/celest_auth/example/lib/main.dart
- packages/celest_auth/lib/src/flows/email_flow.dart
- packages/celest_auth/lib/src/state/auth_state.dart
- packages/celest_core/lib/src/storage/secure/secure_storage.darwin.dart
- Rename `email.signIn` to `email.authenticate` to better align with functionality.
- Add `celest_auth` as a dependency of `celest` so that it can be imported easily in clientgen.
> chore(auth): Clean up

- packages/cedar/LICENSE
- packages/cedar/pubspec.yaml
- packages/cedar_ffi/LICENSE
- packages/cedar_ffi/README.md
- packages/cedar_ffi/pubspec.yaml
- packages/celest_auth/LICENSE
- packages/celest_auth/README.md
- packages/corks/LICENSE
- Adds missing fields to pubspecs
- Ensures every package has a `README` and a `LICENSE` file
> chore(repo): Clean up pubspecs

- .github/workflows/native_storage.yaml
- packages/native/storage/CHANGELOG.md
- packages/native/storage/android/src/main/kotlin/dev/celest/native_storage/NativeStorage.kt
- packages/native/storage/example/integration_test/storage_shared.dart
- packages/native/storage/example/integration_test/storage_test.dart
- packages/native/storage/lib/src/local/local_storage.android.dart
- packages/native/storage/lib/src/local/local_storage.linux.dart
- packages/native/storage/lib/src/local/local_storage.windows.dart
- packages/native/storage/lib/src/local/local_storage_darwin.dart
- packages/native/storage/lib/src/local/local_storage_platform.vm.dart
- packages/native/storage/lib/src/local/local_storage_platform.web.dart
- packages/native/storage/lib/src/memory_storage.dart
- packages/native/storage/lib/src/native/android/jni_bindings.ffi.dart
- packages/native/storage/lib/src/native/windows/windows.dart
- packages/native/storage/lib/src/native_storage_extended.dart
- packages/native/storage/lib/src/secure/secure_storage.android.dart
- packages/native/storage/lib/src/secure/secure_storage.darwin.dart
- packages/native/storage/lib/src/secure/secure_storage.linux.dart
- packages/native/storage/lib/src/secure/secure_storage.windows.dart
- packages/native/storage/lib/src/secure/secure_storage_platform.vm.dart
- packages/native/storage/test/native_storage_test.dart
- The `kSecMatchLimit` flag must always be `kSecMatchLimitAll` to return a list, but this was previously not set in release mode.
- Adds tests for all platforms to check that the keys to be cleared only include those owned by native_storage
> fix(native_storage): Clearing of secure storage on macOS/iOS

- .github/dependabot.yaml
- Removes Cedar packages
- Updates paths for existing packages
> ci: Update dependabot config

- .github/workflows/celest.yaml
- .github/workflows/celest_auth.yaml
- .github/workflows/celest_core.yaml
- .gitignore
- melos.yaml
- packages/celest/example/celest/pubspec.yaml
- packages/celest/example/pubspec.yaml
- packages/celest_auth/example/celest/pubspec.yaml
- packages/celest_auth/example/pubspec.yaml
- packages/celest_auth/pubspec.yaml
- packages/celest_core/pubspec.yaml
- pubspec.yaml
Adds `melos` configuration for managing package linking and development.
> chore(repo): Use `melos` for monorepo dev

- packages/celest/CHANGELOG.md
- packages/celest/lib/src/functions/http/http_header.dart
- packages/celest/lib/src/functions/http/http_query.dart
- packages/celest/pubspec.yaml
Default to the parameter name for unspecified httpQuery/httpHeader names.
> fix: Allow `null` for `@httpQuery` and `@httpHeader` parameters

- .github/workflows/celest_auth.yaml
- packages/celest_auth/CHANGELOG.md
- packages/celest_auth/lib/src/auth_impl.dart
- packages/celest_auth/pubspec.yaml
- packages/celest_auth/test/auth_impl_test.dart
- packages/celest_core/CHANGELOG.md
- packages/celest_core/lib/src/auth/authenticator.dart
- packages/celest_core/lib/src/http/celest_http_client.dart
- packages/celest_core/pubspec.yaml
Use consistent absolute scoping when referring to sections of the native storage to avoid collisions/incorrect storage.
> chore(auth): Disambiguate native storage scoping

- packages/celest_auth/lib/src/auth_impl.dart
- packages/celest_cloud/lib/celest_cloud.dart
- packages/celest_cloud/lib/src/cloud/authentication/authentication_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/cloud.dart
- packages/celest_cloud/lib/src/cloud/cloud_protocol.dart
- packages/celest_cloud/lib/src/cloud/cloud_protocol.grpc.dart
- packages/celest_cloud/lib/src/cloud/cloud_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/operations/operations_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/projects/projects.dart
- packages/celest_cloud/lib/src/cloud/projects/projects_protocol.dart
- packages/celest_cloud/lib/src/cloud/projects/projects_protocol.grpc.dart
- packages/celest_cloud/lib/src/cloud/projects/projects_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/users/users_protocol.http.dart
- packages/celest_cloud/lib/src/grpc.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/auth/v1alpha1/users.pbjson.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/common.pb.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/common.pbjson.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/operations.pbgrpc.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/organizations.pb.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/organizations.pbenum.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/organizations.pbgrpc.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/organizations.pbjson.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/projects.pb.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/projects.pbjson.dart
- packages/celest_cloud/lib/src/proto/operations.dart
- packages/celest_cloud/test/cloud/cloud_test.dart
- packages/celest_core/lib/src/exception/cloud_exception.dart
- packages/celest_core/lib/src/http/celest_http_client.dart
- Add projects service
- Fix HTTP routing
- Add some missing fields
- Clean up some abstractions
> chore(cloud): Clean up

- packages/celest/lib/celest.dart
- packages/celest/lib/src/core/annotations.dart
- packages/celest/lib/src/core/context.dart
- packages/celest/lib/src/core/environment.dart
- packages/celest/lib/src/runtime/gcp/gcp.dart
- packages/celest/lib/src/runtime/http/logging.dart
- packages/celest/lib/src/runtime/http/middleware.dart
- packages/celest/lib/src/runtime/serve.dart
- packages/celest/lib/src/runtime/targets.dart
- packages/celest/pubspec.yaml
Adds a context object which is unique per-request and holds request-specific information. The context will also serve as the global service locator for DI.
> feat(celest): Add request context

- packages/celest/lib/src/auth/auth_provider.dart
- packages/celest/lib/src/config/env.dart
- packages/celest/lib/src/core/context.dart
- packages/celest/lib/src/runtime/auth/auth_middleware.dart
- packages/celest/lib/src/runtime/auth/firebase/firebase_auth_middleware.dart
- packages/celest/lib/src/runtime/auth/firebase/firebase_public_key_store.dart
- packages/celest/lib/src/runtime/auth/firebase/firebase_token_verifier.dart
- packages/celest/lib/src/runtime/auth/supabase/supabase_auth_middleware.dart
- packages/celest/lib/src/runtime/auth/supabase/supabase_token_verifier.dart
- packages/celest/lib/src/runtime/http/logging.dart
- packages/celest/lib/src/runtime/serve.dart
Adds support for using Supabase as an external auth provider.
> feat(auth): Add support for Supabase IDP

- packages/celest/example/celest/client/lib/src/functions.dart
- packages/celest/lib/src/runtime/auth/auth_middleware.dart
- packages/celest/lib/src/runtime/http/cloud_middleware.dart
- packages/celest/lib/src/runtime/http/logging.dart
- packages/celest/lib/src/runtime/http/middleware.dart
- packages/celest/lib/src/runtime/json_utils.dart
- packages/celest/lib/src/runtime/serve.dart
- packages/celest/lib/src/runtime/sse/sse_handler.dart
- packages/celest/lib/src/runtime/targets.dart
- packages/celest_auth/example/celest/client/lib/src/functions.dart
- packages/celest_cloud/lib/src/cloud/base/base_protocol.dart
- packages/celest_core/lib/celest_core.dart
- packages/celest_core/lib/src/events/event_channel.vm.dart
- packages/celest_core/lib/src/exception/cloud_exception.dart
- packages/celest_core/lib/src/exception/serialization_exception.dart
- packages/celest_core/lib/src/serialization/serializer.dart
- packages/celest_core/lib/src/serialization/serializers/cloud_exception_serializer.dart
- packages/celest_core/lib/src/util/json.dart
- packages/celest_core/pubspec.yaml
- Clean up exception type interface and serialization
- Allow non-Map values in event streams
- Add standard `Middleware` interface
- Return `shelf.Response` from targets
> chore: Runtime enhancements

- packages/celest/lib/src/runtime/sse/sse_handler.dart
- packages/celest/lib/src/runtime/targets.dart
- packages/celest_core/lib/src/base/base_protocol.dart
- packages/celest_core/lib/src/events/event_channel.dart
- packages/celest_core/lib/src/events/event_channel.vm.dart
- packages/celest_core/lib/src/events/event_channel.web.dart
- packages/celest_core/lib/src/events/sse/sse_client.dart
- packages/celest_core/lib/src/events/sse/sse_client.web.dart
- packages/celest_core/lib/src/util/json.dart
Fixes SSE and WebSocket handling by not assuming the request/response will always be a Map. This was recently changed to allow arbitrary values to be passed over the sockets.
> fix(runtime): Stream handling

- packages/celest/lib/src/core/context.dart
- packages/celest/test/core/context_test.dart
- Adds tests for `Context` and `ContextValues`
- Prevents misuse of `Context` by disallowing setting values in the root context.
> test(celest): Context tests

- packages/celest/lib/celest.dart
- packages/celest/lib/src/core/context.dart
- packages/celest/lib/src/runtime/auth/supabase/supabase_token_verifier.dart
- packages/celest/lib/src/runtime/configuration.dart
- packages/celest/lib/src/runtime/gcp/gcp.dart
- packages/celest/lib/src/runtime/http/cloud_middleware.dart
- packages/celest/lib/src/runtime/http/logging.dart
- packages/celest/lib/src/runtime/serve.dart
- packages/celest/test/runtime/serve_test.dart
- packages/celest_ast/lib/src/sdk_configuration.dart
This allows generated backends to provide project-specific configuration at startup.
> chore(runtime): Add `setup` parameter to `serve`

- packages/celest/lib/src/runtime/auth/auth_middleware.dart
- packages/celest/lib/src/runtime/auth/firebase/firebase_public_key_store.dart
- packages/celest/lib/src/runtime/auth/firebase/firebase_token_verifier.dart
- packages/celest/lib/src/runtime/auth/supabase/supabase_token_verifier.dart
- packages/celest_cloud/lib/src/cloud/base/base_service.dart
- packages/celest_core/lib/src/base/base_protocol.dart
- packages/celest_core/lib/src/exception/cloud_exception.dart
- packages/celest_core/lib/src/exception/serialization_exception.dart
Celest vends its own `UnimplementedError` type which conforms to `CloudException` but it previously had a different interface than the `dart:core` type so if you imported Celest, any `UnimplementedError()` clauses would need to be changed. This aligns all exception type interfaces to avoid needing to pass explicit `null` to their constructors.
Also fixes the `CloudException.http` and `CloudException.grpc` factories to pass all parameters to delegated constructors.
> chore(core)!: Align `CloudException` interface with stdlib.

- .github/workflows/celest_cloud_auth.yaml
Use macOS for running tests since it has a newer version of SQLite pre-installed
> ci(cloud_auth): Fix test environment

- packages/celest_lints/CHANGELOG.md
- packages/celest_lints/lib/app.yaml
- packages/celest_lints/lib/library.yaml
- packages/celest_lints/pubspec.yaml
- Bump min Dart SDK version to 3.7.
- Update `lints` to `^5.0.0`.
- Update `flutter_lints` to `^5.0.0`.
- Remove `require_trailing_commas` rule (conflicts with Dart 3.7 formatting).
> chore(lints): Update Celest lints for Dart 3.7

- apps/cli/fixtures/fixtures_test.dart
- apps/cli/lib/src/cli.dart
- apps/cli/lib/src/sdk/dart_sdk.dart
- apps/cli/lib/src/sdk/sdk_finder.dart
- apps/cli/test/env/firebase_config_value_solver_test.dart
- apps/cli/test/pub/pub_cache_test.dart
- apps/cli/test/src/sdk/sdk_finder_test.dart
- Remove `Sdk.load` and tests
- Migrate existing tests to `DartSdkFinder`
- Use dependency injection for `DartSdkFinder` instead of relying on global variables.
> chore(cli): Clean up Dart SDK files

- apps/cli/lib/src/commands/start_command.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/cli/lib/src/frontend/child_process.dart
When `--` is passed to `celest start`, run the following command after starting the local environment. For example, you can do
`celest start -- flutter test -d macos` to run tests which depend on Celest running.
> feat(cli): Add support for auxiliary commands to `celest start`

- apps/cli/lib/src/codegen/cloud/cloud_client_generator.dart
- apps/cli/lib/src/codegen/cloud_code_generator.dart
To avoid name clashing between `context` from `package:celest` and the top-level generated `context` variable.
> fix(cli): Use prefixing in `cloud.celest.dart`

- apps/cli/lib/src/codegen/api/entrypoint_generator.dart
This ensures that APIs throw the appropriate error and return the correct status code when a user is not authenticated.
> fix(cli): Ensure `@authenticated` routes require auth with external providers

- packages/celest_auth/lib/src/auth.dart
- packages/celest_auth/lib/src/auth_impl.dart
So that it can be called in generated client code.
> chore(auth): Make `close` part of the public API

- apps/cli/fixtures/standalone/api/client/lib/api_client.dart
- apps/cli/fixtures/standalone/auth/client/lib/auth_client.dart
- apps/cli/fixtures/standalone/data/client/lib/data_client.dart
- apps/cli/fixtures/standalone/env_vars/client/lib/env_vars_client.dart
- apps/cli/fixtures/standalone/exceptions/client/lib/exceptions_client.dart
- apps/cli/fixtures/standalone/flutter/client/lib/flutter_client.dart
- apps/cli/fixtures/standalone/http/client/lib/api_client.dart
- apps/cli/fixtures/standalone/marcelo/client/lib/marcelo_client.dart
- apps/cli/fixtures/standalone/simple/client/lib/simple_client.dart
- apps/cli/fixtures/standalone/streaming/client/lib/streaming_client.dart
- apps/cli/lib/src/codegen/allocator.dart
- apps/cli/lib/src/codegen/client/client_generator.dart
- apps/cli/lib/src/types/dart_types.dart
This is mostly useful in testing when multiple `celest.init` calls are made by closing out the Auth client and creating a new one.
> chore(cli): Add full reset to generated client

- apps/cli/lib/src/compiler/api/local_api_runner.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/cli/lib/src/frontend/child_process.dart
When running `celest start` with an auxiliary command, pass the running server's VM service URI to the command as a Dart define.
This is useful when the auxiliary command is `dart test` or `flutter test` and allows `package:celest_test` to get live updates from the server in an integration test.
> chore(cli): Pass Celest's VM service URI to auxiliary start commands

- packages/celest_test/.gitignore
- packages/celest_test/CHANGELOG.md
- packages/celest_test/README.md
- packages/celest_test/analysis_options.yaml
- packages/celest_test/lib/celest_test.dart
- packages/celest_test/pubspec.yaml
- pubspec.yaml
Adds the initial version of the `celest_test` package for running integration tests with Celest.
> feat: Add `celest_test` package

- packages/celest_test/lib/celest_test.dart
- services/celest_cloud_auth/lib/src/email/email_provider.dart
- services/celest_cloud_auth/lib/src/otp/otp_provider.dart
Adds the ability to monitor email OTP events in `package:celest_test` so that full E2E tests can be performed.
> chore(auth): Add `celest_test` helper for email OTP events

- .github/workflows/celest_auth.yaml
- packages/celest_auth/example/.gitignore
- packages/celest_auth/example/android/.gitignore
- packages/celest_auth/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/celest_auth/example/android/settings.gradle
- packages/celest_auth/example/celest/client/lib/celest_auth_example_client.dart
- packages/celest_auth/example/celest/client/pubspec.yaml
- packages/celest_auth/example/celest/lib/src/generated/auth.celest.dart
- packages/celest_auth/example/celest/lib/src/generated/cloud.celest.dart
- packages/celest_auth/example/celest/lib/src/generated/config.celest.dart
- packages/celest_auth/example/celest/pubspec.yaml
- packages/celest_auth/example/integration_test/integration_test.dart
- packages/celest_auth/example/ios/Podfile.lock
- packages/celest_auth/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/celest_auth/example/lib/main.dart
- packages/celest_auth/example/lib/test_keys.dart
- packages/celest_auth/example/macos/Podfile
- packages/celest_auth/example/macos/Podfile.lock
- packages/celest_auth/example/macos/Runner.xcodeproj/project.pbxproj
- packages/celest_auth/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/celest_auth/example/macos/Runner/AppDelegate.swift
- packages/celest_auth/example/macos/Runner/DebugProfile.entitlements
- packages/celest_auth/example/macos/Runner/Release.entitlements
- packages/celest_auth/example/pubspec.yaml
- packages/celest_auth/example/test_driver/integration_test.dart
- packages/celest_auth/example/web/index.html
- packages/celest_test/lib/celest_test.dart
- packages/celest_test/lib/src/vm_service_factory.dart
- packages/celest_test/pubspec.yaml
- Updates to latest Flutter
- Adds integration test
> chore(auth): Update example

- .github/workflows/celest_auth.yaml
- packages/celest_auth/example/integration_test/integration_test.dart
- Remove macOS integration tests for now, since they'll require a dev cert in CI to run.
- Correct tests for slow I/O
- Add fallback to upload recorded video on failure
> ci: Fix celest_auth tests

- packages/celest/lib/src/runtime/data/connect.dart
- packages/celest/test/runtime/data/connect_test.dart
Allow setting host values for in-memory, file, and remote sources.
> fix(runtime): Treat database host values as DSN strings

- apps/cli/fixtures/standalone/data/goldens/celest.json
- apps/cli/fixtures/standalone/data/lib/src/generated/data.celest.dart
- apps/cli/lib/src/analyzer/celest_analyzer.dart
- apps/cli/lib/src/analyzer/resolver/project_resolver.dart
- apps/cli/lib/src/utils/recase.dart
Use `${DATABASE_NAME}_HOST` and `${DATABASE_NAME}_TOKEN` instead of a hardcoded value.
> fix(cli): Rename database environment variables

- packages/celest_core/CHANGELOG.md
- packages/celest_core/lib/src/exception/cloud_exception.dart
- packages/celest_core/lib/src/proto/google/protobuf/struct.pb.dart
- packages/celest_core/lib/src/proto/google/protobuf/struct.pbenum.dart
- packages/celest_core/lib/src/proto/google/protobuf/struct.pbjson.dart
Adds `toGrpcError` and retain both the gRPC and HTTP status codes for each exception.
> chore(core): Improve gRPC interop in `CloudException`

- packages/celest/lib/src/runtime/data/connect.dart
- packages/celest/lib/src/runtime/data/connect.io.dart
- packages/celest/lib/src/runtime/data/connect.web.dart
Allow passing a `setup` parameter to the DB `connect` functon.
> chore(core): Add `setup` parameter to `connect`

- packages/celest/CHANGELOG.md
- packages/celest/lib/src/core/context.dart
This is used in multiple places now, it has use cases outside `package:celest` anywhere you want to control what the root context zone is, e.g. tests.
> chore(celest): Remove `@internal` from `set Context.root`

- packages/celest_cloud/CHANGELOG.md
- packages/celest_cloud/lib/src/cloud/cloud.dart
- packages/celest_cloud/lib/src/cloud/cloud_protocol.grpc.dart
- Add separate `.http` and `.grpc` dedicated constructors
- Allow specifying an `InternetAddress` for the gRPC host, e.g. a UNIX socket
> chore(cloud): Improve gRPC interface

- .github/workflows/celest.yaml
- .github/workflows/celest_auth.yaml
To avoid the costs of XL runners which are not currently worth it.
> ci: Use smaller macOS runners

- apps/cli/fixtures/fixtures_test.dart
- apps/cli/lib/src/analyzer/celest_analysis_helpers.dart
- apps/cli/lib/src/analyzer/celest_analyzer.dart
- apps/cli/lib/src/analyzer/resolver/project_resolver.dart
- apps/cli/lib/src/commands/uninstall/celest_uninstaller.dart
- apps/cli/lib/src/database/cache/cache_database.dart
- apps/cli/lib/src/init/edits/source_edit.dart
- apps/cli/lib/src/init/edits/source_edit_applier.dart
- apps/cli/lib/src/init/migrations/pubspec_updater.dart
- apps/cli/lib/src/init/project_init.dart
- apps/cli/lib/src/init/project_migrate.dart
- apps/cli/lib/src/init/project_migration.dart
- apps/cli/lib/src/init/project_migrator.dart
- apps/cli/lib/src/project/celest_project.dart
- Abstract some logic around source edits
- Improve flow for `dart fix` (should be rare)
> refactor(cli): Clean up migration logic

- services/celest_cloud_auth/lib/src/database/schema/cloud_auth_users.drift
- services/celest_cloud_auth/lib/src/database/schema/cloud_auth_users.drift.dart
- services/celest_cloud_auth/lib/src/users/users_service.dart
- services/celest_cloud_auth/test/users/users_service_test.dart
Make use of Drift's [features](https://drift.simonbinder.eu/sql_api/drift_files/) to improve performance and correctly add emails + phone numbers to list queries.
> chore(cloud_auth): Improve performance of ListUsers

- apps/cli/lib/src/codegen/api/dockerfile_generator.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/cli/lib/src/project/project_linker.dart
- apps/cli/lib/src/repositories/project_repository.dart
- packages/celest/example/celest/.gitignore
- packages/celest_cloud/lib/src/cloud/cloud.dart
- packages/celest_cloud/lib/src/cloud/project_environments/project_environments_protocol.http.dart
- services/celest_cloud_hub/analysis_options.yaml
- services/celest_cloud_hub/bin/cloud_hub.dart
- services/celest_cloud_hub/bin/deploy_test.dart
- services/celest_cloud_hub/fly.yaml
- services/celest_cloud_hub/lib/src/database/schema/project_environments.drift
- services/celest_cloud_hub/lib/src/database/schema/project_environments.drift.dart
- services/celest_cloud_hub/lib/src/deploy/fly/fly_api.dart
- services/celest_cloud_hub/lib/src/deploy/fly/fly_api.openapi.json
- services/celest_cloud_hub/lib/src/deploy/fly/fly_app_config.dart
- services/celest_cloud_hub/lib/src/deploy/fly/fly_app_config.g.dart
- services/celest_cloud_hub/lib/src/deploy/fly/fly_deployment_engine.dart
- services/celest_cloud_hub/lib/src/gateway/gateway.dart
- services/celest_cloud_hub/lib/src/model/type_registry.dart
- services/celest_cloud_hub/lib/src/services/project_environments_service.dart
- services/celest_cloud_hub/pubspec.yaml
- services/celest_cloud_hub/test/services/project_environments_service_e2e_test.dart
- services/celest_cloud_hub/test/services/project_environments_service_test.dart
Adds a deployment engine using Fly.io to Celest Cloud.
> feat(cloud_hub): Add deployment to fly.io

- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/cli/lib/src/project/celest_project.dart
- examples/tasks/celest/lib/src/database/task_database.g.dart
- examples/tasks/celest/lib/src/generated/data.celest.dart
- packages/celest_cloud/pubspec.yaml
Instead of requiring a separate build_runner dev cycle when using Drift or others, manage a build_runner daemon for the user with `celest start`.
> chore(cli): Run `build_runner` daemon with `celest start`

- apps/cli/pubspec.yaml
v7.4.0 seems to have broken a lot. Upgrade when fixed and when a full element v2 migration can be completed.
> chore(cli): Pin analyzer version

- .github/workflows/celest_cli.yaml
- apps/cli/lib/src/analyzer/celest_analyzer.dart
- apps/cli/lib/src/commands/init_command.dart
- apps/cli/lib/src/commands/start_command.dart
- apps/cli/lib/src/init/project_generator.dart
- apps/cli/lib/src/init/project_init.dart
- apps/cli/lib/src/init/project_migration.dart
- apps/cli/lib/src/init/templates/data_project.dart
- apps/cli/lib/src/init/templates/hello_project.dart
- apps/cli/lib/src/init/templates/project_template.dart
- apps/cli/lib/src/pub/project_dependency.dart
- apps/cli/pubspec.yaml
- apps/cli/test/e2e/e2e_test.dart
- apps/cli/test/e2e/features/templates/data_project.dart
- apps/cli/test/e2e/features/templates/hello_project.dart
- apps/cli/test/init/project_item_test.dart
- Adds two templates to `celest init`: the exiting `hello` template and a `data` template which is a slim version of the `tasks` example project.
- Fixes some false-positive errors when running `celest start` from a generated template where codegen is required.
> feat(cli): Add templates to `celest init`

- apps/cli/bin/celest.dart
- apps/cli/lib/src/commands/status_command.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/project_environments.pb.dart
- packages/celest_cloud/lib/src/proto/celest/cloud/v1alpha1/project_environments.pbjson.dart
- proto/celest/cloud/v1alpha1/project_environments.proto
- services/celest_cloud_hub/.dockerignore
- services/celest_cloud_hub/lib/src/database/schema/operations.drift
- services/celest_cloud_hub/lib/src/database/schema/operations.drift.dart
- services/celest_cloud_hub/lib/src/model/interop.dart
- services/celest_cloud_hub/lib/src/services/project_environments_service.dart
- Adds command to get the status of the Celest project if it's deployed to Celest Cloud.
- Fixes the ability to delete project environments via `celest project-environments delete`.
> feat(cli): Add `celest status` command

- apps/cli/lib/src/commands/cloud_command.dart
- apps/cli/lib/src/commands/organizations/get_organization_command.dart
- apps/cli/lib/src/commands/organizations/list_organizations_command.dart
- apps/cli/lib/src/commands/project_environments/get_project_environment_command.dart
- apps/cli/lib/src/commands/project_environments/list_project_environments_command.dart
- apps/cli/lib/src/commands/projects/get_project_command.dart
- apps/cli/lib/src/commands/projects/list_projects_command.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/cli/lib/src/logging/cli_logger.dart
- Use `package:dart_console` for prompting since it handles control sequences better
- Add structured output to `list` commands
> chore(cli): Clean up console input/output

- apps/cli/lib/src/codegen/api/dockerfile_generator.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/distroless/flutter/build/Dockerfile
- apps/distroless/flutter/build/Dockerfile.old
When creating a Dockerfile with `celest build`, use the distroless Dart + Flutter docker containers for quicker and more reliable images.
> chore(cli): Use distroless Docker containers

- apps/cli/lib/src/types/type_helper.dart
Accidentally deleted this line in analyzer v2 migration.
> fix(cli): Init types on reset

- apps/cli/CHANGELOG.md
- apps/cli/fixtures/standalone/api/goldens/ast.json
- apps/cli/fixtures/standalone/api/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/api/goldens/celest.json
- apps/cli/fixtures/standalone/auth/goldens/ast.json
- apps/cli/fixtures/standalone/auth/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/auth/goldens/celest.json
- apps/cli/fixtures/standalone/data/goldens/ast.json
- apps/cli/fixtures/standalone/data/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/data/goldens/celest.json
- apps/cli/fixtures/standalone/env_vars/goldens/ast.json
- apps/cli/fixtures/standalone/env_vars/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/env_vars/goldens/celest.json
- apps/cli/fixtures/standalone/exceptions/goldens/ast.json
- apps/cli/fixtures/standalone/exceptions/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/exceptions/goldens/celest.json
- apps/cli/fixtures/standalone/flutter/goldens/ast.json
- apps/cli/fixtures/standalone/flutter/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/flutter/goldens/celest.json
- apps/cli/fixtures/standalone/http/goldens/ast.json
- apps/cli/fixtures/standalone/http/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/http/goldens/celest.json
- apps/cli/fixtures/standalone/marcelo/goldens/ast.json
- apps/cli/fixtures/standalone/marcelo/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/marcelo/goldens/celest.json
- apps/cli/fixtures/standalone/streaming/goldens/ast.json
- apps/cli/fixtures/standalone/streaming/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/streaming/goldens/celest.json
- apps/cli/lib/src/version.dart
- apps/cli/pubspec.yaml
- feat: Add templates to `celest init`
- feat: Add `celest status` command
- chore: Update to analyzer model v2
- chore: Use distroless Docker base images
> release(cli): v1.0.10

- packages/celest/CHANGELOG.md
- packages/celest/tools/analyzer_plugin/lib/celest_analyzer_plugin.dart
- packages/celest/tools/analyzer_plugin/lib/src/analyzer_helpers.dart
- packages/celest/tools/analyzer_plugin/pubspec.yaml
- pubspec.yaml
Migrates the bundled analyzer plugin to the v2 element model.
> chore(celest): Migrate analyzer plugin to v2

- packages/celest_core/CHANGELOG.md
- packages/celest_core/pubspec.yaml
- packages/celest_test/CHANGELOG.md
- packages/celest_test/pubspec.yaml
No breaking changes so allow pre-v1 versions as well.
> chore: Bump `web_socket` dependency

- apps/cli/CHANGELOG.md
- apps/cli/fixtures/standalone/api/goldens/ast.json
- apps/cli/fixtures/standalone/api/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/api/goldens/celest.json
- apps/cli/fixtures/standalone/auth/goldens/ast.json
- apps/cli/fixtures/standalone/auth/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/auth/goldens/celest.json
- apps/cli/fixtures/standalone/data/goldens/ast.json
- apps/cli/fixtures/standalone/data/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/data/goldens/celest.json
- apps/cli/fixtures/standalone/env_vars/goldens/ast.json
- apps/cli/fixtures/standalone/env_vars/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/env_vars/goldens/celest.json
- apps/cli/fixtures/standalone/exceptions/goldens/ast.json
- apps/cli/fixtures/standalone/exceptions/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/exceptions/goldens/celest.json
- apps/cli/fixtures/standalone/flutter/goldens/ast.json
- apps/cli/fixtures/standalone/flutter/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/flutter/goldens/celest.json
- apps/cli/fixtures/standalone/http/goldens/ast.json
- apps/cli/fixtures/standalone/http/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/http/goldens/celest.json
- apps/cli/fixtures/standalone/marcelo/goldens/ast.json
- apps/cli/fixtures/standalone/marcelo/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/marcelo/goldens/celest.json
- apps/cli/fixtures/standalone/streaming/goldens/ast.json
- apps/cli/fixtures/standalone/streaming/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/streaming/goldens/celest.json
- apps/cli/lib/src/version.dart
- apps/cli/pubspec.yaml
- fix: Pass `flutter_assets` to backend when using `celest deploy`
- fix: Sentry integration
- fix: Ensure pub cache is fixed during startup
> release(cli): v1.0.10+3

- apps/cli/lib/src/commands/auth/auth_command.dart
- apps/cli/lib/src/commands/auth/login_command.dart
- apps/cli/lib/src/commands/auth/whoami_command.dart
- apps/cli/lib/src/commands/celest_command.dart
Allow logging into the CLI with a token for non-interactive environments.
Also adds a `auth whoami` command for getting the current user info.
> feat(cli): Add `--token` parameter to `auth login`

- .github/workflows/distroless_core.yaml
- apps/cli/lib/src/codegen/api/dockerfile_generator.dart
For consistency with other images
> chore(distroless): Rename core image to celestdev/runtime

- .github/workflows/celest_cli.release.yaml
- apps/cli/tool/linux/deb/DEBIAN/control
- apps/cli/tool/release.dart
Adds a workflow to create a Linux deb installer and tar archive for releases.
> ci: Create Linux installer

- .github/workflows/celest_cli.release.yaml
- apps/cli/tool/release.dart
join([...], '\n') does not in fact create a newline-delimited string...
> ci: Fix release workflow

- apps/cli/lib/src/cli/cli.dart
- apps/cli/tool/linux/celest
- apps/cli/tool/linux/deb/DEBIAN/control
- apps/cli/tool/linux/install
- apps/cli/tool/release.dart
- Adds `install` and `celest` scripts to simplify the installation of Celest CLI on Linux and the execution in headless environments.
- Updates Linux releases with proper deps and architecture
> chore(cli): Add Linux helper scripts

- .github/workflows/celest_cli.e2e.yaml
ubuntu-large is super flaky for some reason and since these on run on commit (async) they don't need to be super fast
> ci: Run e2e tests on smaller runners

- apps/cli/fixtures/fixtures_test.dart
- apps/cli/fixtures/standalone/api/pubspec.yaml
- apps/cli/fixtures/standalone/auth/pubspec.yaml
- apps/cli/fixtures/standalone/data/pubspec.yaml
- apps/cli/fixtures/standalone/env_vars/pubspec.yaml
- apps/cli/fixtures/standalone/exceptions/pubspec.yaml
- apps/cli/fixtures/standalone/flutter/pubspec.yaml
- apps/cli/fixtures/standalone/http/pubspec.yaml
- apps/cli/fixtures/standalone/marcelo/pubspec.yaml
- apps/cli/fixtures/standalone/streaming/pubspec.yaml
- apps/cli/lib/src/cli/stop_signal.dart
- apps/cli/lib/src/commands/celest_command.dart
- apps/cli/lib/src/commands/project/build_command.dart
- apps/cli/lib/src/commands/project/deploy_command.dart
- apps/cli/lib/src/commands/project/init_command.dart
- apps/cli/lib/src/commands/project/start_command.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/cli/lib/src/init/project_creator.dart
- apps/cli/lib/src/init/project_init.dart
- apps/cli/lib/src/repositories/cloud_repository.dart
- Lift up stop signal so that all commands have access to functionality
- Move cloud-related logic to a unified `CloudRepository`
> refactor(cli): Abstract some components

- apps/cli/lib/src/commands/auth/login_command.dart
- apps/cli/pubspec.yaml
Ensure that the primary organization exists when logging in or signing up.
> feat(cli): Ensure primary org creation on login

- apps/cli/lib/src/compiler/api/entrypoint_compiler.dart
- apps/cli/lib/src/sdk/dart_sdk.dart
The `--experimental-cross-compilation` is removed for 3.8 stable so only allow 3.8 stable to avoid issues.
> chore(cli): Update cross-compilation version

- apps/cli/fixtures/apps/firebase/celest/client/pubspec.yaml
- apps/cli/fixtures/apps/firebase/celest/pubspec.yaml
- apps/cli/fixtures/apps/supabase/celest/client/pubspec.yaml
- apps/cli/fixtures/apps/supabase/celest/pubspec.yaml
- apps/cli/fixtures/standalone/api/client/pubspec.yaml
- apps/cli/fixtures/standalone/auth/client/pubspec.yaml
- apps/cli/fixtures/standalone/data/client/pubspec.yaml
- apps/cli/fixtures/standalone/env_vars/client/pubspec.yaml
- apps/cli/fixtures/standalone/exceptions/client/pubspec.yaml
- apps/cli/fixtures/standalone/flutter/client/pubspec.yaml
- apps/cli/fixtures/standalone/http/client/pubspec.yaml
- apps/cli/fixtures/standalone/marcelo/client/pubspec.yaml
- apps/cli/fixtures/standalone/streaming/client/pubspec.yaml
- apps/cli/lib/src/init/project_init.dart
- apps/cli/lib/src/pub/project_dependency.dart
- apps/cli/test/e2e/common/common.dart
- apps/cli/test/e2e/e2e_test.dart
- apps/cli/test/e2e/features/init/init_project_name.dart
- apps/cli/test/e2e/features/init/templates/data_project.dart
- apps/cli/test/e2e/features/init/templates/hello_project.dart
- packages/celest_auth/example/celest/client/pubspec.yaml
- packages/celest_auth/example/celest/pubspec.yaml
- packages/celest_auth/example/pubspec.yaml
- Adds `celest_cloud_core` dependency in more places
- Fixes project initialization in `celest init`
- Add e2e test for `celest init` changes
> test: Fix tests

- .github/workflows/celest_cli.headless.yaml
- apps/cli/lib/src/cli/cli.dart
- apps/cli/tool/linux/celest
- apps/cli/tool/linux/check
- apps/cli/tool/linux/install
And add CI checks to ensure they function properly.
> chore: Update headless scripts

- CONTRIBUTING.md
- README.md
**Description**
This PR aims to add a wiki documentation that a takes a deep dive into what the core architecture and proposition for Celest are. This is especially helpful to create an interactive environment for new contributors (like myself) to get started with contribution by having a deeper understanding of the project at its core. Enabling them to contribute quicker, and overall helps Celest ship faster.
_**Wiki screenshot:**_
> Add deep wiki support

- services/celest_cloud_auth/CHANGELOG.md
- services/celest_cloud_auth/lib/src/database/auth_database_accessors.dart
- services/celest_cloud_auth/lib/src/database/schema/cloud_auth_core.drift
- services/celest_cloud_auth/lib/src/database/schema/cloud_auth_core.drift.dart
When seeding the database or inserting entities across multiple tables, use batches to improve performance. This is required for Turso since transactions have short time limits and can easily timeout when not using batches.
> perf(cloud_auth): Use batches for migrations

- .github/workflows/celest_db_studio.yaml
- packages/celest_db_studio/.gitignore
- packages/celest_db_studio/CHANGELOG.md
- packages/celest_db_studio/README.md
- packages/celest_db_studio/analysis_options.yaml
- packages/celest_db_studio/bin/server.dart
- packages/celest_db_studio/lib/celest_db_studio.dart
- packages/celest_db_studio/lib/src/driver.dart
- packages/celest_db_studio/lib/src/index.html
- packages/celest_db_studio/lib/src/index.js
- packages/celest_db_studio/lib/src/template.dart
- packages/celest_db_studio/lib/src/template.g.dart
- packages/celest_db_studio/pubspec.yaml
- packages/celest_db_studio/test/e2e_test.dart
- packages/celest_db_studio/test/server_test.dart
- packages/celest_db_studio/test/start_server.dart
- pubspec.yaml
Adds a wrapper around Outerbase Studio for Celest databases.
> feat(db_studio): Add DB studio package

- packages/celest/lib/src/runtime/data/celest_database.dart
- services/celest_cloud_hub/bin/cloud_hub.dart
To ensure that HTTP timeouts and retry behavior are centralized and overridable, use the context's HTTP client for Hrana connections.
> chore(celest): Use context HTTP client for DB connections

- .github/workflows/celest_core.yaml
- packages/celest_core/lib/src/exception/cloud_exception.dart
- packages/celest_core/pubspec.yaml
- packages/celest_core/test/exception/cloud_exception_test.dart
The default gRPC import (`package:grpc/grpc_or_grpcweb.dart`) causes DDC to fail compilation. This adds tests to `celest_core` to ensure that it can imported and compiled on DDC.
> chore(core): Ensure DDC compilation

- packages/celest_lints/CHANGELOG.md
- packages/celest_lints/lib/app.yaml
- packages/celest_lints/lib/library.yaml
- packages/celest_lints/pubspec.yaml
The main change is experimenting with replacing `omit_local_variable_types` with [`omit_obvious_local_variable_types`](https://dart.dev/tools/linter-rules/omit_obvious_local_variable_types) and [`specify_nonobvious_local_variable_types`](https://dart.dev/tools/linter-rules/specify_nonobvious_local_variable_types). This change should help improve the readability of code (especially for outside contributors) while not being as verbose as `always_specify_types`.
All changes:
- Update license
- Bump min Dart SDK version to 3.7.
- Add `annotate_redeclares` rule
- Add `invalid_runtime_check_with_js_interop_types` rule
- Add `missing_code_block_language_in_doc_comment` rule
- Replace `omit_local_variable_types` with `omit_obvious_local_variable_types` and …
> feat(lints): Update linter/style preferences

- .github/workflows/celest_auth.yaml
- packages/celest_auth/CHANGELOG.md
- packages/celest_auth/example/analysis_options.yaml
- packages/celest_auth/example/celest/client/lib/celest_auth_example_client.dart
- packages/celest_auth/example/celest/client/lib/src/auth.dart
- packages/celest_auth/example/celest/client/lib/src/functions.dart
- packages/celest_auth/example/celest/client/lib/src/serializers.dart
- packages/celest_auth/example/celest/client/pubspec.yaml
- packages/celest_auth/example/celest/lib/src/functions/greeting.dart
- packages/celest_auth/example/celest/lib/src/generated/auth.celest.dart
- packages/celest_auth/example/celest/lib/src/generated/data.celest.dart
- packages/celest_auth/example/celest/lib/src/project.dart
- packages/celest_auth/example/celest/test/functions/greeting_test.dart
- packages/celest_auth/example/integration_test/integration_test.dart
- packages/celest_auth/example/lib/main.dart
- packages/celest_auth/example/lib/test_keys.dart
- packages/celest_auth/example/pubspec.yaml
- packages/celest_auth/lib/src/auth.dart
- packages/celest_auth/lib/src/auth_impl.dart
- packages/celest_auth/lib/src/flows/auth_flow.dart
- packages/celest_auth/lib/src/flows/email_flow.dart
- packages/celest_auth/lib/src/flows/idp_flow.dart
- packages/celest_auth/lib/src/flows/sms_flow.dart
- packages/celest_auth/lib/src/model/auth_provider_type.dart
- packages/celest_auth/lib/src/model/cloud_interop.dart
- packages/celest_auth/lib/src/model/initial_uri.flutter.dart
- packages/celest_auth/lib/src/state/auth_state.dart
- Applies latest linter/style preferences using `dart fix`
> chore(celest_auth): Update linter/style preferences

- .github/workflows/celest_cloud.yaml
- packages/celest_cloud/CHANGELOG.md
- packages/celest_cloud/lib/src/cloud/authentication/authentication.dart
- packages/celest_cloud/lib/src/cloud/authentication/authentication_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/authentication/session_state.dart
- packages/celest_cloud/lib/src/cloud/base/base_grpc_client.dart
- packages/celest_cloud/lib/src/cloud/base/base_http_client.dart
- packages/celest_cloud/lib/src/cloud/base/base_protocol.dart
- packages/celest_cloud/lib/src/cloud/base/base_service.dart
- packages/celest_cloud/lib/src/cloud/cloud.dart
- packages/celest_cloud/lib/src/cloud/cloud_protocol.grpc.dart
- packages/celest_cloud/lib/src/cloud/cloud_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/operations/operations.dart
- packages/celest_cloud/lib/src/cloud/operations/operations_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/organizations/organizations.dart
- packages/celest_cloud/lib/src/cloud/organizations/organizations_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/project_environments/project_environments.dart
- packages/celest_cloud/lib/src/cloud/project_environments/project_environments_protocol.grpc.dart
- packages/celest_cloud/lib/src/cloud/project_environments/project_environments_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/projects/projects.dart
- packages/celest_cloud/lib/src/cloud/projects/projects_protocol.grpc.dart
- packages/celest_cloud/lib/src/cloud/projects/projects_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/subscriptions/subscriptions.dart
- packages/celest_cloud/lib/src/cloud/subscriptions/subscriptions_protocol.http.dart
- packages/celest_cloud/lib/src/cloud/users/users.dart
- packages/celest_cloud/lib/src/cloud/users/users_protocol.http.dart
- packages/celest_cloud/lib/src/util/operations.dart
- packages/celest_cloud/test/cloud/cloud_test.dart
> chore(cloud): Update linter/style preferences

- apps/distroless/bin/list_sdks.dart
- apps/distroless/flutter/build/build.sh
- apps/distroless/flutter/build/sync.sh
Use prebuilt Dart SDK since the git revision of the /third_party version does not match the prebuilt which causes invalid SDK hash checks when testing against the downloaded Flutter SDK.
> chore(distroless): Try to re-enable beta builds

- apps/cli/fixtures/fixtures_test.dart
- apps/cli/fixtures/standalone/flutter/goldens/ast.json
- apps/cli/fixtures/standalone/flutter/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/flutter/goldens/celest.json
- apps/cli/lib/src/codegen/api/dockerfile_generator.dart
And remove platform limitation in Dockerfile generator.
> chore(cli): Re-enable flutter tests

- .github/workflows/celest.yaml
- packages/celest/CHANGELOG.md
- packages/celest/example/celest/client/lib/example_client.dart
- packages/celest/example/celest/client/lib/src/functions.dart
- packages/celest/example/celest/client/lib/src/serializers.dart
- packages/celest/example/lib/main.dart
- packages/celest/pubspec.yaml
- packages/celest/tools/analyzer_plugin/lib/celest_analyzer_plugin.dart
- packages/celest/tools/analyzer_plugin/lib/src/analyzer_helpers.dart
- refactor: Move `connect` method to `CelestDatabase` class
- fix: Analyzer plugin cannot be part of workspace
- chore: Bump Dart SDK constraint to `^3.7.0`
- chore: Reformat with Dart 3.7
> release(celest): v1.0.6

- apps/cli/CHANGELOG.md
- apps/cli/fixtures/standalone/api/client/lib/api_client.dart
- apps/cli/fixtures/standalone/auth/client/lib/auth_client.dart
- apps/cli/fixtures/standalone/data/client/lib/data_client.dart
- apps/cli/fixtures/standalone/data/lib/src/database/task_database.drift.dart
- apps/cli/fixtures/standalone/env_vars/client/lib/env_vars_client.dart
- apps/cli/fixtures/standalone/exceptions/client/lib/exceptions_client.dart
- apps/cli/fixtures/standalone/flutter/client/lib/flutter_client.dart
- apps/cli/fixtures/standalone/http/client/lib/api_client.dart
- apps/cli/fixtures/standalone/marcelo/client/lib/marcelo_client.dart
- apps/cli/fixtures/standalone/streaming/client/lib/streaming_client.dart
- apps/cli/lib/src/codegen/client/client_generator.dart
Adds the ability for apps to set a dart define of `CELEST_ENVIRONMENT` instead of passing the environment to `celest.init`.
For example, you can now run `flutter run -d chrome --dart-define=CELEST_ENVIRONMENT=production` to get the same behavior as `celest.init(environment: CelestEnvironment.production)`.
> feat(cli): Allow overriding client environment with Dart define

- .github/workflows/celest.yaml
- .github/workflows/celest_auth.yaml
The normal runners experience timeouts way too often.
> ci: Use XL macOS runners for integration tests

- examples/firebase/pubspec.yaml
- examples/gemini/pubspec.yaml
- examples/openai/pubspec.yaml
- examples/supabase/pubspec.yaml
- examples/tasks/pubspec.yaml
- packages/celest/example/pubspec.yaml
So that dependency resolution works even when celest_ast hasn't been published yet.
> chore(examples): Add dependency_override for celest_ast

- .github/workflows/celest.yaml
- .github/workflows/celest_ast.yaml
- .github/workflows/celest_auth.yaml
- .github/workflows/celest_cli.e2e.yaml
- .github/workflows/celest_cli.headless.yaml
- .github/workflows/celest_cli.yaml
- .github/workflows/celest_cloud.yaml
- .github/workflows/celest_cloud_auth.yaml
- .github/workflows/celest_cloud_core.yaml
- .github/workflows/celest_cloud_hub.yaml
- .github/workflows/celest_core.yaml
- .github/workflows/examples.yaml
To suppress warnings from CodeQL about missing permissions in workflows.
> ci: Set default permissions

- apps/cli/lib/src/sdk/dart_sdk.dart
- apps/distroless/dart/test/test-docker.sh
The latest Dart SDKs have renamed `vm_platform_strong` to `vm_platform`.
> chore(cli): `vm_platform_strong` renamed to `vm_platform`

- apps/cli/CHANGELOG.md
- apps/cli/lib/src/init/project_init.dart
- apps/cli/test/init/project_init_test.dart
The `==` for directory objects doesn't succeed leading to an infinite loop when reaching the root directory.
> fix(cli): Always halt when seraching for pubspec.yaml

- apps/cli/CHANGELOG.md
- apps/cli/lib/src/sdk/dart_sdk.dart
There seems to be an issue with the Dart SDK shipped with the latest Flutter betas where cross-compiling results in a VM snapshot error.
> fix(cli): Only cross-compile with non-Flutter SDKs

- apps/cli/CHANGELOG.md
- apps/cli/fixtures/standalone/api/goldens/ast.json
- apps/cli/fixtures/standalone/api/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/api/goldens/celest.json
- apps/cli/fixtures/standalone/auth/goldens/ast.json
- apps/cli/fixtures/standalone/auth/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/auth/goldens/celest.json
- apps/cli/fixtures/standalone/data/goldens/ast.json
- apps/cli/fixtures/standalone/data/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/data/goldens/celest.json
- apps/cli/fixtures/standalone/env_vars/goldens/ast.json
- apps/cli/fixtures/standalone/env_vars/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/env_vars/goldens/celest.json
- apps/cli/fixtures/standalone/exceptions/goldens/ast.json
- apps/cli/fixtures/standalone/exceptions/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/exceptions/goldens/celest.json
- apps/cli/fixtures/standalone/flutter/goldens/ast.json
- apps/cli/fixtures/standalone/flutter/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/flutter/goldens/celest.json
- apps/cli/fixtures/standalone/http/goldens/ast.json
- apps/cli/fixtures/standalone/http/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/http/goldens/celest.json
- apps/cli/fixtures/standalone/marcelo/goldens/ast.json
- apps/cli/fixtures/standalone/marcelo/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/marcelo/goldens/celest.json
- apps/cli/fixtures/standalone/streaming/goldens/ast.json
- apps/cli/fixtures/standalone/streaming/goldens/ast.resolved.json
- apps/cli/fixtures/standalone/streaming/goldens/celest.json
- apps/cli/lib/src/version.dart
- apps/cli/pubspec.yaml
- feat: Allow overriding client environment with Dart define
- fix: Searching parent directories for a `pubspec.yaml` file always halts now
- fix: Only cross-compile with non-Flutter Dart SDKs
- chore: Use new Flutter version file
- chore: Update dependencies
> release(cli): v1.0.14

- .github/workflows/distroless_dart.yaml
- .github/workflows/distroless_flutter.yaml
Only build & replace images when `replace` is passed as input.
> ci(distroless): Add `replace` input

- apps/cli/CHANGELOG.md
- apps/cli/lib/src/compiler/api/local_api_runner.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- When compilation errors are flagged, accept the result from the frontend server so that we can call `compile` again
- Reload all isolates when performing a hot reload
> fix(cli): Improve reload handling

- apps/cli/CHANGELOG.md
- apps/cli/lib/src/analyzer/project_parser.dart
- apps/cli/lib/src/codegen/client_code_generator.dart
- apps/cli/lib/src/codegen/code_outputs.dart
- apps/cli/lib/src/frontend/celest_frontend.dart
- apps/cli/lib/src/project/celest_project.dart
- apps/cli/lib/src/pub/project_dependency.dart
When auth or a database are added to a project for the first time, ensure that the necessary dependencies are added to the pubspec and resolvable by the analyzer before analysis.
> fix(cli): Ensure all dependencies are correctly resolved
